name: mediadb-models-tests

run-name: mediaDB-models unittests
on: [push]
jobs:

    run-tests:
        runs-on: ubuntu-latest
        container: rgroux/python-dev-ubuntu@sha256:d4e62e22990f19ba1adeadc11e1ab2348a50a2cd4f409b8ac04ad7eec2d6af6b
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: unittests mediadb-models
              run: cd mediadb-models/ && tox -r
    