name: mediadb-models-tests

run-name: mediaDB-models unittests
on: [push]
jobs:

    run-tests:
        runs-on: ubuntu-latest
        container: rgroux/python-dev-ubuntu@sha256:d4e62e22990f19ba1adeadc11e1ab2348a50a2cd4f409b8ac04ad7eec2d6af6b
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: unittests mediadb-models
              run: cd mediadb-models/ && tox -r

            - name: coverage badge
              uses: tj-actions/coverage-badge-py@v2
              with:
                # Output path to write the 
                # coverage badge. 
                # Type: string
                # Default: "coverage.svg"
                output: 'coverage.svg'
                # Overwrite an existing coverage badge.
                # Type: boolean
                # Default: "true"
                overwrite: 'true'
                # Current working directory
                working-directory: 'mediadb-models'
            
            - name: verify changed files
              uses: tj-actions/verify-changed-files@v16
              id: verify-changed-files
              with:
                files: coverage.svg

            - name: commit coverage badge
              if: steps.verify-changed-files.outputs.files_changed == 'true'
              run: |
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add coverage.svg
                git commit -m "updated coverage badge"

            - name: psuh coverage badge
              if: steps.verify-changed-files.outputs.files_changed == 'true'
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}

    